### ISSUE TITLE
Keyboard input change

### ISSUE THREAD

**Issue by farfromrefug** [VegaBobo/Language-Selector#1]
Do you have the possibility to add per app language input ? That would be awesome

**Comment by VegaBobo** [comment]
Thanks for suggestion, but unfortunatelly i don't know if that is possible, i really don't know about how IMEs change their language, if it is managed by the keyboard app itself, there is a high change that it isn't possible without root or some implementation that give us the target application authority, if it is managed by OS, then we might me able to do something, but IMO the behavior would be kinda "bad", because we would need to detect every app behavior (when its opened, when its closed, when its resumed..) to change keyboard language depending on app preferences, which is kinda sketchy.

Anyway, that is not a bad idea, and it would be really useful, but i think is more easy to do so with other solution, like Xposed (eg. by hooking into desired keyboard app methods, detect once its visible, and change IME language directly from the keyboard app itself), that seems less sketchy to get working, and even more flexible.

Thats are my thoughts, which might be super inaccurate, if someone have other ideas about this behavior, feel free to share them here, but by now, ill be marking this a not planned, since, at least by now, i have no plans to add Xposed support to this app.
